name: Build and Release

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      # - name: Eslint
        # run: npm run lint

      - name: Build
        run: npm run build

      - name: Archive Production
        run: zip -r wallpaperengine-theunsentproject.zip dist

      - name: Add Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: wallpaperengine-theunsentproject.zip
